apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-poi
  namespace: api
  labels:
    app: ti-poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ti-poi
  template:
    metadata:
      labels:
        app: ti-poi
        aadpodidbinding: take2podidentity
    spec:
      containers:
      - name: ti-poi
        image: registrypby9755.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-team2keyvault-e14d775c-4ac5-4d43-b01e-bcfc060572a2
---
apiVersion: v1
kind: Service
metadata:
  name: ti-poi
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: ti-poi

