apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-tripviewer
  namespace: web
  labels:
    app: ti-tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ti-tripviewer
  template:
    metadata:
      labels:
        app: ti-tripviewer
    spec:
      containers:
      - name: ti-tripviewer
        image: registrypby9755.azurecr.io/tripinsights/tripviewer:1.1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://ti-trips.api.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://ti-userprofile.api.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: ti-tripviewer
  namespace: web
spec:
  selector:
    app: ti-tripviewer
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

