apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-tripviewer
  namespace: web
  labels:
    app: ti-tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ti-tripviewer
  template:
    metadata:
      labels:
        app: ti-tripviewer
    spec:
      containers:
      - name: ti-tripviewer
        image: registrypby9755.azurecr.io/tripinsights/tripviewer:1.1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://ti-trips.api.svc.cluster.local:9911"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://ti-userprofile.api.svc.cluster.local:9911"
---
apiVersion: v1
kind: Service
metadata:
  name: ti-tripviewer
  namespace: web
spec:
  selector:
    app: ti-tripviewer
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ti-tripviewer
  namespace: api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: ti-tripviewer.0957189954974d819320.ukwest.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ti-tripviewer
                port:
                  number: 80
          - path: /api/user/healthcheck
            pathType: Prefix
            backend:
              service:
                name: ti-userprofile
                port:
                  number: 80
