apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-userjava
  namespace: api
  labels:
    app: ti-userjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ti-userjava
  template:
    metadata:
      labels:
        app: ti-userjava
    spec:
      containers:
      - name: ti-userjava
        image: registrypby9755.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
                secretKeyRef:
                  key: sql-user-value
                  name: sql
        - name: SQL_PASSWORD
          valueFrom:
                secretKeyRef:
                  key: sql-password-value
                  name: sql
        - name: SQL_SERVER
          valueFrom:
                secretKeyRef:
                  key: sql-server-value
                  name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: ti-userjava
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ti-userjava

