apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api
type: Opaque
stringData:
  sql-user-value: "sqladminpBy9755"
  sql-password-value: "mJ5bz2Mb8"
  sql-server-value: "sqlserverpby9755.database.windows.net"